# models/sources.yml
version: 2

sources:
  - name: public
    database: erp_db  # Replace with your database name
    schema: public
    tables:
      - name: Noora_Messages
      - name: Noora_Statuses
